### ISSUE TITLE
Praca Domowa 1 - odpowiedzi

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/warsztaty-matlab#1]
Tutaj wrzucajcie screenshoty z pracy domowej 1
:hamster:

**Comment by mmagnuski** [comment]
Oto moje rozwiązanie pracy domowej. :smile: 
![moja praca domowa](https://cloud.githubusercontent.com/assets/8452354/10338884/bb258c18-6d08-11e5-8c07-8640b947365b.PNG)

**Comment by tomsitoms** [comment]
Uwaga, wrzucam :+1:  : 
![pd1_20151008](https://cloud.githubusercontent.com/assets/9054258/10375654/1507fabc-6dfa-11e5-94a7-89b824547fb6.JPG)

**Comment by WandaZ** [comment]
praca domowa 1
![mwsnap022](https://cloud.githubusercontent.com/assets/12087134/10412759/4adc8b7a-6f90-11e5-929a-30421fd55002.gif)

**Comment by szielinska** [comment]
![sabina_zielinska_praca_domowa_1](https://cloud.githubusercontent.com/assets/12383328/10416389/a096d5f4-7015-11e5-9cd3-487a91aa29fd.jpg)

**Comment by bpietka** [comment]
Oto moje rozwiązanie pracy domowej. :smiley: 
![bp](https://cloud.githubusercontent.com/assets/11992773/10425771/9ebef8c2-70da-11e5-8b2e-ddd609a8d828.png)

**Comment by soniaszka** [comment]
<img width="1169" alt="zrzut ekranu 2015-10-12 o 16 20 40" src="https://cloud.githubusercontent.com/assets/12235244/10430055/4b5d4440-70fd-11e5-98a7-2bb589a6f07c.png">

**Comment by Juliajools** [comment]
Julia & Julia 

![praca_domowa_adamus](https://cloud.githubusercontent.com/assets/12091033/10432887/753f5dfa-710e-11e5-8796-c43b29633f80.png)

**Comment by mmagnuski** [comment]
@Juliajools - wszystko git, tylko macierz `A` zaadresuj względem długości swojego imienia i nazwiska, nie mojego :smiley:

**Comment by mmista** [comment]
Miłosz Miśta

![milosz_mista_praca_1](https://cloud.githubusercontent.com/assets/12235266/10434252/bd3851c0-7118-11e5-8d86-535ac071ecf7.jpg)

**Comment by elorek** [comment]
Ewa Lorek
![praca domowa](https://cloud.githubusercontent.com/assets/12393450/10434894/9f728c42-711c-11e5-97b7-f99394f670df.png)

**Comment by mchylinski94** [comment]
![pracadomowa1](https://cloud.githubusercontent.com/assets/12235272/10437351/b3777cce-712c-11e5-9583-ec1dc0f8e80e.png)

**Comment by bbednarz** [comment]
![praca domowa2](https://cloud.githubusercontent.com/assets/12235251/10437732/7795c80c-712f-11e5-8d63-09077dcb355d.png)

**Comment by ZbyszekZ** [comment]
![mwsnap179](https://cloud.githubusercontent.com/assets/12087396/10438374/8f3fe6e6-7133-11e5-84b3-20c508c18041.jpg)

**Comment by koda246** [comment]
![moja praca domowa](https://cloud.githubusercontent.com/assets/11992716/10439717/1ee9eb18-713c-11e5-9132-9f9179a3e0df.png)

**Comment by Juliajools** [comment]
aj, gapiostwo! 

![zrzut ekranu 2015-10-13 o 00 29 03](https://cloud.githubusercontent.com/assets/12091033/10440650/7a5d769a-7141-11e5-9c36-3f7408c85b70.png)

**Comment by jwisniewska** [comment]
![justyna wisniewska](https://cloud.githubusercontent.com/assets/12298536/10441272/5e6815b6-7147-11e5-892d-8a203aab6f38.jpg)

**Comment by Searlas87** [comment]
![zrzut ekranu 2015-10-13 o 01 10 48](https://cloud.githubusercontent.com/assets/12298151/10441275/66f6783a-7147-11e5-9efb-3dc6e1068e75.png)

**Comment by mmagnuski** [comment]
@mmista przydałby się taki wombat theme do Juliabox :+1:

**Comment by wrzos** [comment]
tadam! :cactus: :muscle: 

![pracadomowa](https://cloud.githubusercontent.com/assets/15103106/10450595/982debdc-719b-11e5-9b27-13b79c946f08.PNG)

**Comment by kabel001** [comment]
![krystyna_bartos_praca_domowa](https://cloud.githubusercontent.com/assets/12097679/10450666/1cc4c17c-719c-11e5-8e2f-d451c749e225.png)

**Comment by KamilJedynak** [comment]
Kamil Jedynak
![praca domnowa](https://cloud.githubusercontent.com/assets/15105121/10453452/6f03a772-71ac-11e5-815e-5a0b983d09dc.png)

**Comment by EdSkamor** [comment]
Jakub Kojemski
![screen shot 2015-10-13 at 13 23 48](https://cloud.githubusercontent.com/assets/12235154/10453585/ae60bfbc-71ad-11e5-8058-5f6753087c74.png)

**Comment by jrafalski** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/12886817/10462317/5d2208b4-71de-11e5-8908-f05af0ede0d8.JPG)

**Comment by Kbondaruk** [comment]
![pd](https://cloud.githubusercontent.com/assets/15105997/10498718/6ea12c70-72cc-11e5-9e3f-cc17ad98af83.jpg)

**Comment by Vespith** [comment]
![ms - zadanie mat lab](https://cloud.githubusercontent.com/assets/12097661/10548780/4c3a4410-743d-11e5-8c4a-68d082b7ea2a.png)
