### ISSUE TITLE
Hej.

### ISSUE THREAD

**Issue by bbednarz** [mmagnuski/warsztaty-matlab#2]
Bo w tutorialach są schematy dla pętli, i innych zagadnień, ale czy np można wstawić wszystkie wzory lub zakres zapytań, które nas obowiązują pod egzamin. Bo obecnie czasami to jest zgadywanie, uczymy się myśleć, ale na zajęciach fajnie jest wiedzieć czego się można spodziewać, a my moglibyśmy w domu przepracować wszystkie alternatywy i to może zwiększyć efektywność pracy z materiałem na zajęciach. Bo na razie czasem mam wrażenie, że my zgadujemy a lepiej jest to mieć na zaś przećwiczone. Bo te tematy wymagają sporego czasu pracy w domu i tak.

**Comment by mmagnuski** [comment]
Ok, pomyślę nad czymś takim.

**Comment by mmagnuski** [comment]
Nie jestem do końca pewien, co masz na myśli, może porozmawiamy dziś po zajęciach? 
Jeżeli chodzi o kartkówki to na kartkówkach zawsze będą analogiczne rzeczy do tych, które robiliśmy dotychczas, zwykle na tyle proste aby dało się je zrobić w ok 10 minut. 
Na teście końcowym tak samo - tyle że będzie kilka zadań i więcej czasu.
Chyba, że chodzi o to, aby materiały tzn "notatki" były bardziej detaliczne?

**Comment by mmagnuski** [comment]
Będę w przyszłości starał się dokumentować wszystko w miarę dokładnie w notatkach i tutorialach video. Otwierajcie kolejne issues gdyby coś było niejasne. :rabbit:
