### ISSUE TITLE
Poprawy

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/warsztaty-matlab#4]
Drodzy studenci, czeka nas (Was) jeszcze szaleństwo popraw.
Preferuję jeden termin, na który wszyscy by się umówili. Proponuję takie opcje:

| dzień | godziny |
| --- | --- |
| wtorek | 12:00 - 13:00 |
| wtorek | 13:45 - 15:15 |
| czwartek | 12:00 - 13:00 |
| czwartek | 15:30 - 17:00 |

Zapraszam do dyskutowania i najlepiej jednogłośnego wyboru.
Możecie głosować, ale możecie również używać względem siebie nawzajem (a nawet mnie) siły perswazji.

**Comment by Vespith** [comment]
10.12.15  - Czwartek - 15:30 - 17:00 ;) 

Maciej.S

**Comment by mmagnuski** [comment]
jak tutaj pusto...

**Comment by kabel001** [comment]
10.12.15 - Czwartek - 15:30 - 17:00 dla mnie też ok :)
Krystyna Bartos

**Comment by mmagnuski** [comment]
Jest drobny problem - po moich zajęciach w sali S207 są kolejne. Poprawa musiała by być w innej sali a co za tym idzie - moglibyście symulować matlaba w Waszych głowach bądź przynieść własne matlaby na laptopach.
Czy tylko dwie osoby są zainteresowane? Bo mógłbym Was po prostu odpytać, bez konieczności przygotowywania nowego testu.

**Comment by Vespith** [comment]
Proponował bym przełożyć poprawę na przyszły tydzień , bo w tym wszyscy mamy dużo zaliczeń:). Osób chcących poprawiać jest wiele, ale tylko dwie osoby się tu wypowiedziały.

**Comment by mmagnuski** [comment]
Ok, może być przyszły tydzień.
