### ISSUE TITLE
nowe poprawy

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/warsztaty-matlab#5]
Drodzy studenci, czeka nas (Was) jeszcze szaleństwo popraw.
Preferuję jeden termin, na który wszyscy by się umówili. Proponuję takie opcje:

| dzień | godziny |
| --- | --- |
| poniedziałek | dowolna godzina |
| wtorek | po 15:15 |
| środa | dowolna godzina |

**Comment by jrafalski** [comment]
Nie ma możliwości zaliczenia tego egzaminu drogą online? Skoro możemy mieć własne notatki to i tak wyjdzie na to samo myślę...

**Comment by jrafalski** [comment]
Ale jeśli nie to ja preferuję wtorek 15:30

**Comment by mmagnuski** [comment]
Online nie mam kontroli nad czasem i tym czy problemy są rozwiązywane indywidualnie. Poprawa powinna przebiegać w formie zbliżonej do poprawianego testu zresztą.

**Comment by jrafalski** [comment]
czyli wtorek 15:30?

**Comment by bbednarz** [comment]
Mi pasuje bardziej poniedziałek 15:30 :)
Wtorek i środa nie dam rady.

**Comment by jrafalski** [comment]
to jak będzie Mikołaj? @mmagnuski

**Comment by mmagnuski** [comment]
Miały powtarzać 4 osoby, nie wszyscy się wypowiedzieli. @jrafalski - my i tak będziemy pewnie robić poprawę pogadankowo, więc nie musi to być zgodne z terminem jaki uzgodni reszta.

**Comment by kabel001** [comment]
a może wtorek po zajęciach - 11:45?

**Comment by kabel001** [comment]
Czy jeżeli poprawia się tylko kartkówkę z pętli to wchodzi w grę poprawa po zajęciach? Bo to trwało jakieś 5 min :)

**Comment by mmagnuski** [comment]
Tak, poprawka pętli może być krótko po zajęciach.

**Comment by Vespith** [comment]
Witaj Mikołaj, na naszej facebookowiej grupie naszej grupy:) wiele osób prosi o poprawę po świętach, jak na razie mobilizują się żeby to tu napisać , i mam nadzieje że wszyscy się wypowiedzą do jutra na tym git hubowym issues w związku z tą prośbą. Bo z tego co widzimy to jest nas więcej niż czworo, tylko "budzimy się w różnych terminach". ;)

**Comment by kabel001** [comment]
Ja również przyłączam się do prośby :)

**Comment by mmagnuski** [comment]
Dla mnie to nie problem - może być po świętach.

**Comment by jrafalski** [comment]
to ja też po ;) Wesołych!

**Comment by bbednarz** [comment]
TO ja też :)
A przy okazji wesołych świąt, jak kogoś jutro ma nie być na zajęciach :)

**Comment by mmagnuski** [comment]
Jutro na pewno będą wszyscy :)

**Comment by jrafalski** [comment]
Mnie nie będzie, rano mam badania na Banacha i fizycznie się nie wyrobię...

**Comment by jrafalski** [comment]
Czy możemy się umówić na najbliższy wtorek, godzinę 12:00?

**Comment by bbednarz** [comment]
We wtorek o 12 robimy projekty z ET więc tam będzie parę osób, które chcą się poprawiać.
Więc realnie wtorek tak, ale np 14?
Zrobilibyśmy sobie swoje badania wzajemnie a potem można śmiało robić poprawę :)

**Comment by jrafalski** [comment]
Dla mnie ok.

**Comment by mmagnuski** [comment]
Ok, dowiem się czy sala jest wolna.

**Comment by jrafalski** [comment]
i jak z tą poprawą jutro? odbędzie się?

**Comment by mmagnuski** [comment]
Zarezerwowałem salę w oknie czasowym `13:45 - 15:15`. Teraz jeszcze muszę przygotować  poprawę, ech

**Comment by jrafalski** [comment]
oby łatwą :)
