### ISSUE TITLE
problem z pracą domową 2

### ISSUE THREAD

**Issue by mchylinski94** [mmagnuski/warsztaty-matlab#7]
wklejam takie cudo do mojego matlaba:

``` matlab
cd ('C:\Users\TOS\Desktop\matlab\wombat\dane_twarze')
n = randi([5 30],1,1)
vec = dir('*.set')
fls = losuj_n(vec, n)
l_fls = length(fls)
dane = cell(l_fls*2, 1)
cond = {'face_180', 'car_180'};
Ncond = length(cond)
cfg = [];
for s = 1:l_fls
EEG = pop_loadset(fls(s).name);
eeg = eeg2ftrip(EEG);
for c = 1:Ncond
cfg.trial = ktory_war(EEG, cond{c});
dane{(s-1)*Ncond + c} = ft_timelockanalysis(cfg, eeg);
end
end
stat = licz_stat(dane);
```

wszystko pięknie idzie i działa ale jak zaglądam do stat to tam jest wszędzie NaN, to ma tak być? czy coś jest w tym nie tak?

**Comment by mmagnuski** [comment]
Wszędzie w `stat` są `NaN` tzn gdzie - każdym polu? Dla wybranego pola możesz sprawdzić jaka jest proporcja `NaN`ów w ten sposób:

``` matlab
pole = 'tutaj_nazwa_pola_z_NaNami';
ktore_nany = isnan(stat.(pole));
proporcja_nanow = mean(ktore_nany(:));
```

Sprawa wygląda jednak zastanawiająco. Będę wdzięczny za listę plików, które wylosowałeś - będę mógł zdebugować. Najlepiej gdybyś wkleił zawartość następujących zmiennych: `n`, `fls`, `Ncond`, inne jak dasz radę.
Czy pojawiają się jakieś błędy? Jakie komunikaty wypluwa FieldTrip?

**Comment by mchylinski94** [comment]
Wyrzuca takie coś:
Warning: adding C:\Users\TOS\Desktop\matlab\wombat\fieldtrip\external\spm8 toolbox to your MATLAB path 
found 0 positive clusters in observed data
found 0 negative clusters in observed data
Warning: no clusters were found in the observed data 

> In clusterstat (line 242)
>   In ft_statistics_montecarlo (line 356)
>   In ft_timelockstatistics (line 181)
>   In licz_stat (line 27) 
> using a cluster-based method for multiple comparison correction
> the returned probabilities and the thresholded mask are corrected for multiple comparisons
> the call to "ft_timelockstatistics" took 9 seconds
> a w zipie są te wszystkie dane
> [wszystko.zip](https://github.com/mmagnuski/warsztaty-matlab/files/93666/wszystko.zip)

**Comment by mmista** [comment]
U mnie to samo... poddaje się...

face_0', 'car_180

Taki błąd : 

Warning: no clusters were found in the observed data 

> In clusterstat (line 242)
>   In ft_statistics_montecarlo (line 356)
>   In ft_timelockstatistics (line 181)
>   In licz_stat (line 27) 
> Warning: Multiple versions of eeglab on your path will confuse FieldTrip 
> In ft_warning (line 181)
> Warning: one version of eeglab is found here: D:\wombat\eeglab13_5_4b\eeglab13_5_4b\plugins\dipfit2.3\eeglab2fieldtrip.m
> Warning: You probably used addpath(genpath('path_to_fieldtrip')), this can lead to unexpected behaviour. See
> http://fieldtrip.fcdonders.nl/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path
> Warning: Function iscolumn has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential
> name conflict.

I też same NaN'y w stat

tu wszystkie dane :

https://drive.google.com/file/d/0B_gggwYycBeFRVdyWDUxeXlyam8/view?usp=sharing

**Comment by mmagnuski** [comment]
Sprawdzam :mag:  , nie traćcie sił. :octopus: Jestem łaskawy i przyjmę prace domowe oddane w przyszłym tygodniu (obecnie już wkroczyliśmy weń) też. :)

To że nie ma klastrów pozytywnych bądź negatywnych to nie jest wielki problem. To wręcz chleb powszedni badacza - więc dobrze się wcześnie z tym oswoić. :wink:

**Comment by mmagnuski** [comment]
Btw - dzięki za pliki z matlaba. Na przyszłość: można zapisać wiele plików na raz, wystarczy zaznaczyć wszystkie, które chcemy zapisać (ctrl-click na przykład), i dopiero wtedy wygrać `save as`

**Comment by mmagnuski** [comment]
Faktycznie, same NaNy. Coś jest źle. (na razie takie mało pomocne odkrycie :smile:  )
Na zajęciach też był w pewnym momencie podobny problem i jak zrobiliśmy prostszą pętlę po osobach to było ok. Dziwne - jutro będę wiedział jak zaradzić.

**Comment by mmagnuski** [comment]
Pierwsza moja hipoteza: losujemy pliki ze zwracaniem więc mogą być powtórki, co może namieszać fieldtripowi w głowie (w zmiennych wysłanych przez @mmista powtórek jest akurat sporo - 9 plików się powtarza mniej więcej).
Zobaczcie czy tak samo Wam wyjdzie gdy w kodzie po:

``` matlab
fls = losuj_n(vec, n);
```

Zrobicie:

``` matlab
fls = unique(fls);
```

**Comment by mchylinski94** [comment]
Jak to dodałem to mam takie errory:
Undefined function 'sort' for input arguments of type 'struct'.

Error in unique>uniqueR2012a (line 183)
        sortA = sort(a);

Error in unique (line 87)
    [varargout{1:nlhs}] = uniqueR2012a(varargin{:});

**Comment by mmagnuski** [comment]
Aj, sorry:

``` matlab
[~, ind] = unique({fls.name});
fls = fls(ind).name;
```

**Comment by mmagnuski** [comment]
Ja już idę spać, jutro wrócę do Waszych problemów.

**Comment by mchylinski94** [comment]
Tym razem mam to 
Struct contents reference from a non-struct array object.
:)

**Comment by mmagnuski** [comment]
(`fls` widocznie przestało być u Ciebie strukturą, puść jeszcze raz:  

``` matlab
vec = dir('*.set')
fls = losuj_n(vec, n)
```

I dopiero potem to co pisałem wcześniej

**Comment by koda246** [comment]
nie może mi znaleźć funkcji "pop_loadset". Właśnie ja jej też nie mogę znaleźć :) Wiem że to banalny problem, ale zawiesiłem się w tym miejscu

**Comment by mmagnuski** [comment]
A masz eeglaba? 
Na początku piszesz:

``` matlab
eeglab
braintools
```

Te dwa pakiety są potrzebne do analizy. Jeżeli ich nie masz - `eeglaba` można ściągnąć googlując a `braintools` z mojego githuba.

**Comment by koda246** [comment]
okej, dzięki z tym sobie już poradziłem) ale teraz mam dokładnie taki sam problem, jak u Michała. Zrobiłem wszystko jak pisałeś wyżej a jednak zostało to:

found 0 positive clusters in observed data
found 0 negative clusters in observed data
Warning: no clusters were found in the observed data 

> In clusterstat (line 242)
>   In ft_statistics_montecarlo (line 356)
>   In ft_timelockstatistics (line 181)
>   In licz_stat (line 27)

**Comment by mmagnuski** [comment]
Za chwilę sprawdzę dokładnie i poinformuje jak rozwiązać.

**Comment by mmagnuski** [comment]
:exclamation: Już wiem! :boom: 

Nie zauważyłem wcześniej, że w kodzie jest błąd:
funkcja `ft_timelockanalysis` przymuje w `cfg` opcję `trials` (nie `trial`), a więc fieldtrip brał wszystkie triale   dla każdej osoby dwa razy: raz jako pierwszy, a raz jako drugi warunek. W efekcie nie było absolutnie żadnych różnic między jednym a drugim "warunkiem" - różnica zero dla każdej osoby, a więc i odchylenie standardowe w grupie - zero. W związku z tym statystyki się wykrzaczały, bo nie było absolutnie żadnej zmienności.

**Rozwiązanie:**
Zamiast linijki:

``` matlab
cfg.trial = ktory_war(EEG, cond{c});
```

wpiszcie:

``` matlab
cfg.trials = ktory_war(EEG, cond{c});
```

łatwo takie głupotki przeoczyć, a to mniej więcej 85% błędów jakie zdarzają się przy programowaniu.

**Comment by mmagnuski** [comment]
A - i zachęcam do tego abyście skorzystali z `plot_time_elec` (pochodzi z pakietu `braintools`):

``` matlab
plot_time_elec(stat);
```

W nagrodę za trud analiz dostajecie ładny obrazek:
![cluster_plot](https://cloud.githubusercontent.com/assets/8452354/12390456/7eae13c6-bde0-11e5-9d61-99319bba9a77.PNG)

**Comment by koda246** [comment]
Wszystko działa!!! Dzięki wielkie, jesteś geniuszem)

**Comment by mmagnuski** [comment]
BTW, w powyższym obrazku widać problem związany z referencją.
Jeżeli chcecie go pozbyć, zaraz po wczytaniu pliku `EEG` możecie dodać do kodu:

``` matlab
EEG = reref_to_avg(EEG);
```

Wtedy wszystkie pliki będą miały referencję do średniej i wykres będzie wyglądał zupełnie inaczej.

**Comment by mchylinski94** [comment]
jest pięknie działa ;)

**Comment by ZbyszekZ** [comment]
Taka mała literka  .....  "s" ,  sama "genetycznie nieco krzywa"  a   tyle wyprostowała :))
Ale .....
zwykle jest wszystko OK , jednak od czasu do czasu, gdy podamy ostatnie polecenie:

plot_time_elec(stat);

zamiast ładnego rysunku  wyskakuje:

![mwsnap005](https://cloud.githubusercontent.com/assets/12087396/12395891/8c28ea3e-be04-11e5-9eb5-4f9e24662650.jpg)

Nie jestem pewien,  ale dodanie polecenia  :

EEG = reref_to_avg(EEG);  

chyba pozwoliło namierzyć problem .
To polecenie też działa dobrze ..... dopóki nie trafi na   plik : CAT301 task2

wtedy:

![mwsnap004](https://cloud.githubusercontent.com/assets/12087396/12395970/246a252e-be05-11e5-834c-b3551e62ebf1.jpg)

Czy pik z danymi  CAT301 task2 ma jakiś problem ???

**Comment by mmagnuski** [comment]
Odnośnie tego ostatniego polecenia - kiedy nie wychodzi? Możesz przesłać `stat` dla którego nie działa? Ostatnio zmieniałem trochę w funkcjach z których korzysta `plot_time_elec` i mogłem był coś namieszać...
Odnośnie `CAT301 task2` - widocznie plik nie ma zdefiniowanej elektrody referencyjnej. Najszybciej/najłatwiej będzie zamiast to naprawiać - wyrzucić go z analizy. Jeżeli jednak chcecie go naprawiać możecie tuż przed `reref_to_avg` dodać:

``` matlab
if strcmp(EEG.filename, 'CAT301 task2.set')
    [EEG.chanlocs.ref] = deal('Cz');
end
```

to powinno załatwić problem.

**Comment by ZbyszekZ** [comment]
Bawiłem się tym wczoraj wieczorem i dziś rano.
Na błąd związany z plotowaniem  niestety nie natrafiłem.
Nie jest on więc związany z plikiem  CAT301 task2.

Jedyny dowcip związany z plikiem   CAT301 task2 to zacinanie się
przetwarzanie danych na tym pliku gdy
w skrypcie mamy polecenie:

EEG = reref_to_avg(EEG);

ale dodanie :

 if strcmp(EEG.filename, 'CAT301 task2.set')
    [EEG.chanlocs.ref] = deal('Cz');

rozwiązuje problem tego pliku,  dane są przetwarzane, z plotowaniem też
niema problemu.

Jeśli uda mi się trafić na ten "dowcip" z plotowaniem zapiszę i podeślę
stat.

W dniu 18 stycznia 2016 23:52 użytkownik Mikolaj Magnuski <
notifications@github.com> napisał:

**Comment by mmagnuski** [comment]
Ok!
